// File generated by Antigravity to support Multi-Platform Firebase initialization.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXpwF7WCqAtI5YsiSFOJ3N1ekQ0UNTsTw',
    appId: '1:1018814514644:ios:0b2c0d21c6ad3d96f68241',
    messagingSenderId: '1018814514644',
    projectId: 'resqnnect-3b59e',
    storageBucket: 'resqnnect-3b59e.firebasestorage.app',
    iosBundleId: 'com.yummyjoy.resqnnect',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcvrDsJDImdoGixaaHMmgHS3fyp3vjdL4',
    appId: '1:1018814514644:web:052d86a8ca7e0614f68241',
    messagingSenderId: '1018814514644',
    projectId: 'resqnnect-3b59e',
    authDomain: 'resqnnect-3b59e.firebaseapp.com',
    storageBucket: 'resqnnect-3b59e.firebasestorage.app',
    measurementId: 'G-8238GJBXVN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcvrDsJDImdoGixaaHMmgHS3fyp3vjdL4',
    appId: '1:1018814514644:android:484ed47fc2e5f732f68241',
    messagingSenderId: '1018814514644',
    projectId: 'resqnnect-3b59e',
    storageBucket: 'resqnnect-3b59e.firebasestorage.app',
  );
}
